name: syncfusion_officecore
description: Syncfusion Flutter Office Core is a dependant library for Syncfusion Flutter XlsIO, written natively in Dart for creating Excel from scratch.
version: 24.1.41
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_officecore

environment:
  sdk: ">=2.17.0 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
    git:
      url: https://github.com/jonasbadstuebner/syncfusion-flutter-widgets.git
      ref: 012fca10356e88d28b68b53c423478265a2b7d8d
      path: packages/syncfusion_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter
