name: syncfusion_pdfviewer_web
description: Web platform implementation of the Flutter PDF Viewer library that lets you view the PDF documents seamlessly and efficiently.
version: 21.2.5
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_pdfviewer_web

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.3.0
  syncfusion_pdfviewer_platform_interface:
    git:
      url: https://github.com/jonasbadstuebner/syncfusion-flutter-widgets.git
      ref: 4f83d3a5d7c2f311156c3c56be9f8a4eacc5734f
      path: packages/syncfusion_pdfviewer_platform_interface
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
     web:
        pluginClass: SyncfusionFlutterPdfViewerPlugin
        fileName: pdfviewer_web.dart
