name: syncfusion_officechart
description: Syncfusion Flutter Office Chart is a library written natively in Dart for creating Office charts from scratch.
version: 24.1.41
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_officechart

environment:
  sdk: ">=2.17.0 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  xml: ">=5.1.0 <7.0.0"
  archive: ">=3.1.2 <4.0.0"
  syncfusion_flutter_xlsio: 
    git:
      url: https://github.com/jonasbadstuebner/syncfusion-flutter-widgets.git
      ref: 4f83d3a5d7c2f311156c3c56be9f8a4eacc5734f
      path: packages/syncfusion_flutter_xlsio
  
dev_dependencies:
  flutter_test:
    sdk: flutter 
