name: syncfusion_flutter_barcodes
description: Flutter Barcodes generator library is used to generate and display data in the machine-readable, industry-standard 1D and 2D barcodes.
version: 24.1.41 
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_barcodes

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
    git:
      url: https://github.com/jonasbadstuebner/syncfusion-flutter-widgets.git
      ref: 4f83d3a5d7c2f311156c3c56be9f8a4eacc5734f
      path: packages/syncfusion_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

 
