name: syncfusion_flutter_maps
description: A Flutter Maps library for creating beautiful, interactive, and customizable maps from shape files or WMTS services to visualize the geographical area.
version: 23.2.5
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_maps

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_core:
    git:
      url: https://github.com/jonasbadstuebner/syncfusion-flutter-widgets.git
      ref: 4f83d3a5d7c2f311156c3c56be9f8a4eacc5734f
      path: packages/syncfusion_flutter_core
      
  http: ^1.0.0
  vector_math: ">=2.1.0 <=3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
