name: syncfusion_flutter_signaturepad
description: The Flutter Signature Pad widget allows you to capture smooth and more realistic signatures through drawn gestures and save it as an image.
version: 24.1.41 
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_signaturepad

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core:
    git:
      url: https://github.com/jonasbadstuebner/syncfusion-flutter-widgets.git
      ref: 4f83d3a5d7c2f311156c3c56be9f8a4eacc5734f
      path: packages/syncfusion_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
